-- AlterEnum
ALTER TYPE "SecurityEventType" ADD VALUE IF NOT EXISTS 'ADMIN_LOGIN_PASSWORD_SUCCESS';
ALTER TYPE "SecurityEventType" ADD VALUE IF NOT EXISTS 'ADMIN_MFA_SUCCESS';
ALTER TYPE "SecurityEventType" ADD VALUE IF NOT EXISTS 'ADMIN_MFA_FAILED';
ALTER TYPE "SecurityEventType" ADD VALUE IF NOT EXISTS 'ADMIN_MFA_ENROLLED';
ALTER TYPE "SecurityEventType" ADD VALUE IF NOT EXISTS 'ADMIN_MFA_DISABLED';

-- AlterTable
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "totpSecretEncrypted" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "totpEnabled" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "totpVerifiedAt" TIMESTAMP(3);
