ALTER TYPE "SecurityEventType" ADD VALUE IF NOT EXISTS 'ADMIN_LOGIN_SUCCESS';
ALTER TYPE "SecurityEventType" ADD VALUE IF NOT EXISTS 'ADMIN_LOGIN_FAILED';
ALTER TYPE "SecurityEventType" ADD VALUE IF NOT EXISTS 'FILE_UPLOAD_ACCEPTED';
ALTER TYPE "SecurityEventType" ADD VALUE IF NOT EXISTS 'FILE_UPLOAD_REJECTED';
ALTER TYPE "SecurityEventType" ADD VALUE IF NOT EXISTS 'SESSION_REVOKED';
ALTER TYPE "SecurityEventType" ADD VALUE IF NOT EXISTS 'SESSION_EXPIRED';

ALTER TABLE "SecurityEvent" ADD COLUMN "userId" TEXT;
ALTER TABLE "SecurityEvent" ADD COLUMN "metadata" JSONB;

CREATE INDEX "SecurityEvent_userId_createdAt_idx" ON "SecurityEvent"("userId", "createdAt");

ALTER TABLE "SecurityEvent" ADD CONSTRAINT "SecurityEvent_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
